// Generated by CoffeeScript 1.8.0
(function () {
  var app, brow, bundle, express, io, pull, server, util, zmq;

  brow = require("browserify-express");

  express = require("express");

  app = express();

  server = require("http").Server(app);

  io = require("socket.io")(server);

  zmq = require("zmq");

  util = require("util");

  server.listen(8765, function () {
    return console.log('Express server listening on port: 8765');
  });

  app.use(express["static"]("" + __dirname + "/public"));

  app.set("view engine", "jade");

  app.set("view options", {
    layout: false
  });

  app.set("views", "./server/views");

  console.log(__dirname + '/client/boot.js');

  bundle = brow({
    entry: __dirname + '/client/boot.js',
    mount: '/boot.js',
    verbose: true,
    minify: false,
    bundle_opts: {
      debug: true
    },
    ignore: ['optional.js']
  });

  console.log(util.inspect(bundle));

  app.use(bundle);

  require("./server/routes/url").load(app);

  io.sockets.on("connection", function (socket) {

    /*
     *# client boot stuff
     */
    return socket.emit("hello");
  });

  pull = zmq.socket("pull");

  pull.bind("tcp://127.0.0.1:3456", function () {
    return pull.on("message", function (data) {
      return io.sockets.emit("message", data.toString("utf-8"));
    });
  });

}).call(this);